version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9001:3000
    volumes:
      - ./src:/workspace
    working_dir: /workspace
    command: yarn start